spring:
  application:
    name: user-manage
  datasource:
    url: jdbc:mysql://localhost:3306/busi?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

server:
  port: 8081
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:1111/eureka/