spring:
  application:
    name: zuul
server:
  port: 7003
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: user-manage
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka/



