
spring:
  application:
    name: config-servier
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenpanpan0809/springcloud-config
          username: chenpanpan0809
          password: 0809chen
server:
  port: 7001
eureka:
  client:
    service-url:
      deafultZone: http://localhost:1111/eureka/
